name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Get PR diff
      - name: Get PR Diff
        run: |
          git fetch origin main
          git diff origin/main...HEAD > diff.txt

      # 3. Install dependencies
      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install openai requests

      # 4. Send diff to OpenAI
      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python3 - <<'EOF'
          import os, openai

          with open("diff.txt") as f:
              diff = f.read()

          openai.api_key = os.getenv("OPENAI_API_KEY")

          response = openai.ChatCompletion.create(
              model="gpt-4o-mini",
              messages=[
                  {"role": "system", "content": "You are a strict senior code reviewer. Review the PR diff and give concise, actionable suggestions."},
                  {"role": "user", "content": f"Review this PR diff:\n{diff}"}
              ]
          )

          feedback = response["choices"][0]["message"]["content"]

          with open("review.md", "w") as f:
              f.write(feedback)
          EOF

      # 5. Post review as PR comment
      - name: Post review comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body-file review.md


